accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'accounts'

urlpatterns = [
    path('login/',login_view, name = 'login'),
    path('logout/',logout_view, name = 'logout'),
    path('signup/',signup_view, name = 'signup'),
    path('password_change/', password_change, name = 'password_change'),

    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog, name = 'home'),
    path('category/<str:cat_name>', blog, name='category'),
    path('tag/<str:tag_name>', blog, name='tag'),
    path('author/<str:author_username>', blog, name='author'),
    path('search/', search, name='search'),
    path('<int:pid>', blog_single, name = 'single'),
    path('test/', test)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from blog.feeds import LatestEntriesFeed
# from website.views import maintenance

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}

urlpatterns = [
    # re_path(r'^.*$', maintenance),
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
        
    ),
    
    re_path(r'^robots\.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("blog/rss/feed/", LatestEntriesFeed()),
    # need this line for reset password with email with django auth views
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', home_view, name = 'index'),
    path('about', about_view, name = 'about'),
    path('contact', contact_view, name = 'contact'),
    path('newsletter', newsletter_view, name = 'newsletter'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(max_length=255, unique=True, null=False, blank=False)
    # USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []
    class Meta:
        pass
        
    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms  
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')  

    class Meta:  
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')  

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm
from django.urls import reverse
from django.contrib import messages
from accounts.forms import CustomUserCreationForm

User = get_user_model()


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request, data=request.POST)

            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')

                user = authenticate(username=username, password=password)
                    
                if user is not None:
                    login(request, user)
                    messages.add_message(request, messages.SUCCESS, 'You Loged In Successfuly')
                    return redirect('/')

                else:
                    messages.add_message(request, messages.WARNING, 'Are You Signed Up?')
            else:
                messages.add_message(request, messages.ERROR, 'This User Is Not Valid !!!')


        form = AuthenticationForm()
        context = {'form':form}
        return render(request, 'accounts/login.html', context)
    else:
        return redirect('/')


@login_required
def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'You Loged Out')

    return redirect('/')


def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'You Signed Up Successfuly\nPlease Log In')
                return redirect('/accounts/login')
            else:
                messages.add_message(request, messages.ERROR, 'Operation Failed\nTry Again')

        form = CustomUserCreationForm()
        context = {'form':form}
        return render(request, 'accounts/signup.html', context)
    else:
        return redirect('/')


@login_required
def password_change(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(user=request.user, data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                messages.add_message(request, messages.SUCCESS, 'You\'re Password Changed Successfuly')

                logout(request)

                return redirect('/accounts/login')
            else:
                messages.add_message(request, messages.ERROR, 'Operation Failed')

        form = PasswordChangeForm(request)
        context = {'form':form}
        return render(request, 'accounts/password_change_form.html', context)
    else:
        
        return redirect('/') 

templates/accounts/login.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-7 col-lg-5">
                    <div class="login-wrap p-4 p-md-5">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4">Login</h3>
                        {% include 'messages.html' %}
                        <form action="{% url 'accounts:login' %}" class="login-form" method="post">
                            {% csrf_token %}
                            
                            <div class="form-group">
                                <input type="text" class="form-control rounded-left" name= "username" placeholder="Username/Email" required>
                            </div>
                            <div class="form-group d-flex">
                                <input type="password" class="form-control rounded-left" name= "password" placeholder="Password"
                                    required>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary rounded submit px-3">Login</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">Remember Me
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="{% url 'accounts:password_reset' %}">Forgot Password</a>
                                </div>
                            </div>
                            <a class="text-center mb-4"  href="{% url 'website:index' %}">Back</a>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816"
        integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw=="
        data-cf-beacon='{"rayId":"7db2a6065dbb1e31","version":"2023.4.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
        crossorigin="anonymous"></script>
</body>

</html>

templates/accounts/password_change_form.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <title>Change Password</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-7 col-lg-5">
                    <div class="login-wrap p-4 p-md-5">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4">Change Password</h3>
                        {% include 'messages.html' %}
                        <form action="{% url 'accounts:password_change' %}" class="login-form" method="post">
                            {% csrf_token %}                            
                            <div class="form-group">
                                <input type="password" class="form-control rounded-left" name= "old_password" placeholder="Old Password" required>
                            </div>
                            <div class="form-group d-flex">
                                <input type="password" class="form-control rounded-left" name= "new_password1" placeholder="New Password"
                                    required>
                            </div>
                            <div class="form-group d-flex">
                              <input type="password" class="form-control rounded-left" name= "new_password2" placeholder="New Password Confirmation"
                                  required>
                            </div>
              
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary rounded submit px-3">Confirm</button>
                            </div>
                            <a class="text-center mb-4"  href="{% url 'website:index' %}">Back</a>
                            <div class="form-group d-md-flex">
                            </div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816"
        integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw=="
        data-cf-beacon='{"rayId":"7db2a6065dbb1e31","version":"2023.4.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
        crossorigin="anonymous"></script>
</body>

</html>

templates/accounts/signup.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <title>Sign Up</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-7 col-lg-5">
                    <div class="login-wrap p-4 p-md-5">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4">Sign Up</h3>
                        {% include 'messages.html' %}
                        <form action="{% url 'accounts:signup' %}" class="login-form" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control rounded-left" name= "username" placeholder="Username" required>
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control rounded-left" name= "email" placeholder="email" required>
                            </div>
                            <div class="form-group d-flex">
                                <input type="password" class="form-control rounded-left" name= "password1" placeholder="Password"
                                required>
                            </div>
                            <div class="form-group d-flex">
                                <input type="password" class="form-control rounded-left" name= "password2" placeholder="Confirm Password"
                                required>
                            </div>
         
                            <div class="form-group">
                                <button type="submit"
                                    class="form-control btn btn-primary rounded submit px-3">Signup</button>
                            </div>
                            <a class="text-center mb-4"  href="{% url 'website:index' %}">Back</a>     
                        </form>
        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816"
        integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw=="
        data-cf-beacon='{"rayId":"7db2a6065dbb1e31","version":"2023.4.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
        crossorigin="anonymous"></script>
</body>

</html>