accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'accounts'

urlpatterns = [
    path('login/',login_view, name = 'login'),
    path('logout/',logout_view, name = 'logout'),
    path('signup/',signup_view, name = 'signup'),
    path('password_change/', password_change, name = 'password_change'),

    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog, name = 'home'),
    path('category/<str:cat_name>', blog, name='category'),
    path('tag/<str:tag_name>', blog, name='tag'),
    path('author/<str:author_username>', blog, name='author'),
    path('search/', search, name='search'),
    path('<int:pid>', blog_single, name = 'single'),
    path('test/', test)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from blog.feeds import LatestEntriesFeed
# from website.views import maintenance

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}

urlpatterns = [
    # re_path(r'^.*$', maintenance),
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
        
    ),
    
    re_path(r'^robots\.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("blog/rss/feed/", LatestEntriesFeed()),
    # need this line for reset password with email with django auth views
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', home_view, name = 'index'),
    path('about', about_view, name = 'about'),
    path('contact', contact_view, name = 'contact'),
    path('newsletter', newsletter_view, name = 'newsletter'),
]

templates/base.html
{% load static %}
{% load compress %}

	<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static 'img/fav.png' %}">
		<!-- Author Meta -->
		<meta name="author" content="colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>MyFirstDjangoProject</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
			<!--
			CSS
			============================================= -->
			{% compress css %}

			<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
			<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">				
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">							
			<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">				
			<link rel="stylesheet" href="{% static 'css/main.css' %}">

			{% endcompress %}
		</head>
		<body>	
			<header id="header">
				
				<div class="header-top">
					<div class="container">

						{% include 'messages.html' %}
						
						<div class="row align-items-center">
							<div class="col-lg-6 col-sm-6 col-6 header-top-left">
								<ul>
									{% if request.user.is_authenticated %}

										<li><a href="#">Loged In as ({{request.user.username}})</a></li>
										<li><a href="{% url 'accounts:logout' %}">Logout</a></li>
										<li><a href="{% url 'accounts:password_change' %}">Change Password</a></li>

									{% else %}

										<li><a href="{% url 'accounts:login' %}">Login</a></li>
										<li><a href="{% url 'accounts:signup' %}">Signup</a></li>

									{% endif %}
								</ul>			
							</div>
							<div class="col-lg-6 col-sm-6 col-6 header-top-right">
								<div class="header-social">
									<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
							</div>
						</div>
					</div>			  					
				</div>
			</div>
			<div class="container main-menu">
				<div class="row align-items-center justify-content-between d-flex">
					<div id="logo">
						<a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
					</div>
					<nav id="nav-menu-container">
						<ul class="nav-menu">
							<li><a href="{% url 'website:index' %}">Home</a></li>
							<li><a href="{% url 'website:about' %}">About</a></li>
							<li><a href="{% url 'blog:home' %}">Blog</a></li>				          		          
							<li><a href="{% url 'website:contact' %}">Contact</a></li>
				        </ul>
					</nav><!-- #nav-menu-container -->					      		  
				</div>
			</div>
			
			</header><!-- #header -->
			
            {% block content %}



            {% endblock %}
			
			<!-- start footer Area -->		
			<footer class="footer-area section-gap">
				<div class="container">

					<div class="row">
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>About Agency</h6>
								<p>
									The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point 
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Navigation Links</h6>
								<div class="row">
									<div class="col">
										<ul>
											<li><a href="{% url 'website:index' %}">Home</a></li>
											<li><a href="#">Feature</a></li>
											<li><a href="#">Services</a></li>
											<li><a href="#">Portfolio</a></li>
										</ul>
									</div>
									<div class="col">
										<ul>
											<li><a href="#">Team</a></li>
											<li><a href="#">Pricing</a></li>
											<li><a href="{% url 'blog:home' %}">Blog</a></li>
											<li><a href="{% url 'website:contact' %}">Contact</a></li>
										</ul>
									</div>										
								</div>							
							</div>
						</div>							
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Newsletter</h6>
								<p>
									For business professionals caught between high OEM price and mediocre print and graphic output.									
								</p>								
								<div>
									<form action="{% url 'website:newsletter' %}" method="post" class="subscription relative">
										{% csrf_token %}
										<div class="input-group d-flex flex-row">
											<input name="email" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
											<button type="submit" class="btn bb-btn"><span class="lnr lnr-location"></span></button>		
										</div>								
										<div class="mt-10 info"></div>
									</form>
			
								
									
								</div>


							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">InstaFeed</h6>
								<ul class="instafeed d-flex flex-wrap">
									<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
								</ul>
							</div>
						</div>						
					</div>

					<div class="row footer-bottom d-flex justify-content-between align-items-center">
						<p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>
			<!-- End footer Area -->	
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>		
			
			{% compress js %}
			<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="{% static 'js/popper.min.js' %}"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>			
 			<script src="{% static 'js/jquery-ui.js' %}"></script>					
  			<script src="{% static 'js/easing.min.js' %}"></script>			
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>	
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>						
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>					
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>							
			<script src="{% static 'js/mail-script.js' %}"></script>	
			<script src="{% static 'js/main.js' %}"></script>	

			{% endcompress %}
		</body>
	</html>

templates/maintenance.html
<!doctype html>
<title>Site Maintenance</title>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
<style>
  html, body { padding: 0; margin: 0; width: 100%; height: 100%; }
  * {box-sizing: border-box;}
  body { text-align: center; padding: 0; background: #d6433b; color: #fff; font-family: Open Sans; }
  h1 { font-size: 50px; font-weight: 100; text-align: center;}
  body { font-family: Open Sans; font-weight: 100; font-size: 20px; color: #fff; text-align: center; display: -webkit-box; display: -ms-flexbox; display: flex; -webkit-box-pack: center; -ms-flex-pack: center; justify-content: center; -webkit-box-align: center; -ms-flex-align: center; align-items: center;}
  article { display: block; width: 700px; padding: 50px; margin: 0 auto; }
  a { color: #fff; font-weight: bold;}
  a:hover { text-decoration: none; }
  svg { width: 75px; margin-top: 1em; }
</style>

<article>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 202.24 202.24"><defs><style>.cls-1{fill:#fff;}</style></defs><title>Asset 3</title><g id="Layer_2" data-name="Layer 2"><g id="Capa_1" data-name="Capa 1"><path class="cls-1" d="M101.12,0A101.12,101.12,0,1,0,202.24,101.12,101.12,101.12,0,0,0,101.12,0ZM159,148.76H43.28a11.57,11.57,0,0,1-10-17.34L91.09,31.16a11.57,11.57,0,0,1,20.06,0L169,131.43a11.57,11.57,0,0,1-10,17.34Z"/><path class="cls-1" d="M101.12,36.93h0L43.27,137.21H159L101.13,36.94Zm0,88.7a7.71,7.71,0,1,1,7.71-7.71A7.71,7.71,0,0,1,101.12,125.63Zm7.71-50.13a7.56,7.56,0,0,1-.11,1.3l-3.8,22.49a3.86,3.86,0,0,1-7.61,0l-3.8-22.49a8,8,0,0,1-.11-1.3,7.71,7.71,0,1,1,15.43,0Z"/></g></g></svg>
    <h1>... به زودی</h1>
    <div>
        <p> این وبسایت در حال بروزرسانی می باشد و به زودی دردسترس خواهد بود. با تشکر</p>
        <p>"ali-dehkhodaei.ir" تیم پشتیبانی</p>
    </div>
</article>

templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <div class="container-fluid p-0">
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="True">&times;</span>
            </button>
            {{ message }}
        </div>
        </div>
    {% endfor %}
</ul>
{% endif %}